name = "CoordinateConverterGK"
uuid = "d77a50d3-17ea-48e4-bb1c-35f220bfae06"
authors = ["Takuya Miyashita"]
version = "0.4.0"

[compat]
julia = "1.3, 1.4, 1.5, 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
